# -*- coding: utf-8 -*-
"""Netflix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNSZVYLWUHos7fucIjrg5fIfPGV-Zn0X

Import Libraries
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

df=pd.read_csv('netflix.csv')

"""Basic Inspection"""

df.head()

"""###Business Objective

####Netflix want to decide

1.   What type of content to produce.
2.   which genres perform better.
3. understand country-wise content strategy.
4. identify growth opportunities globally.
"""

import matplotlib.pyplot as plt
import seaborn as sns

df.head()

df.describe()

df.shape

df.info()

"""What observe:


*   Number of rows:8807
*   Number of column:12
*   Datatype:int

Convert Categorical Columns
"""

cat_cols = ['type','rating']
for col in cat_cols:
    df[col] = df[col].astype('category')

cat_cols

"""Check Missing Values"""

df.isnull().sum()

"""Missing value in column:


*   director
*   cast
*   country
*   date_added
*   rating
*   duration

Movies vs TV Shows
"""

df['type'].value_counts()

"""Top Countries"""

df['country'].value_counts().head(10)

"""Top Ratings"""

df['rating'].value_counts()

"""It's clear:

1. Netflix has more movie the TV shows
2. USA contributes the highest content
3. TV-MA and TV-14 has highest rating

We must "unnest" columns like:
*   Cast
*   Director
*   Country
*   Listed_in (Genre)

Because they have multiple value sepreated by comma

Split Columns
"""

df['country'] = df['country'].str.split(',')
df_country = df.explode('country')

df['listed_in'] = df['listed_in'].str.split(',')
df_genre = df.explode('listed_in')

df['cast'] = df['cast'].str.split(',')
df_cast = df.explode('cast')

df['director'] = df['director'].str.split(',')
df_director = df.explode('director')

df_genre

"""###Visual Analysis

Release Year Distribution
"""

plt.figure()
sns.histplot(df['release_year'], bins=30)
plt.show()

"""Insight:



*   Massive increase in content after 2015
*   Shows aggressive expansion strategy


"""

df_movies = df[df['type']=='Movie'].copy()
df_movies['duration'] = df_movies['duration'].str.replace(' min','', regex=False)
df_movies.dropna(subset=['duration'], inplace=True)
df_movies['duration'] = df_movies['duration'].astype(int)

plt.figure(figsize=(10, 6))
sns.histplot(df_movies['duration'], bins=30)
plt.title('Distribution of Movie Durations')
plt.xlabel('Duration (minutes)')
plt.ylabel('Number of Movies')
plt.show()

"""Insight:

Most movie are Durations between 80-120

Movies vs TV Shows countplot
"""

plt.figure()
sns.countplot(x='type', data=df)
plt.show()

"""Movie dominating over TV-shows

###Content Added Over Years
"""

df['date_added'] = pd.to_datetime(df['date_added'], format='mixed')
df['year_added'] = df['date_added'].dt.year

plt.figure(figsize=(12,6))
sns.countplot(x='year_added', data=df)
plt.title('Content Added Over Years')
plt.xlabel('Year Added')
plt.ylabel('Number of Titles')
plt.xticks(rotation=90)
plt.show()

"""Insight :

*   Rapid increase between 2016 to 2019

###Type vs Release Year
"""

plt.figure()
sns.boxplot(x='type', y='release_year', data=df)
plt.show()

"""Insight:


*   In recent year TV-Show are more then movie.
*   Netflix shifted focus towards TV-show.

Mising value
"""

df['director']=df['director'].fillna('Unknown')
df['cast']=df['cast'].fillna('Unknown')
df['country']=df['country'].fillna('Unknown')

df['date_added'] = df['date_added'].astype(object).fillna('Unknown')
df['rating'] = df['rating'].cat.add_categories('Unknown')
df['rating'] = df['rating'].fillna('Unknown')
df['duration'] = df['duration'].fillna('Unknown')

df.isnull().sum()

df['listed_in']=df['listed_in'].fillna('Unknown')

df.isnull().sum()

df['year_added']=df['year_added'].fillna('Unknown')

df.isnull().sum()

"""Missing categorical values replaced with "Unknown"."""

sns.boxplot(x=df_movies['duration'])

"""Few are long duration movie

###Observation :

1.   Netflix has more Movies than TV Shows overall.
2.   However, in recent years, TV Shows are increasing rapidly.
3. Majority content comes from USA.
4. Content production increased drastically after 2015.
5. Most movies are around 90-120 minutes.
6. TV-MA rating dominates

###patterns

*   Netflix expanded aggressively after 2015.
*   Strong dominance in US market.
*   Recent shift toward TV Shows.
*   Adult content drives engagement.

###Content Strategy

*   Increase production of TV Shows since trend is rising.
*   Focus on 8-10 episode series.
*   Continue producing 90-120 min movies.
*   Invest in India, South Korea, and European content.
*   Produce region-specific original shows.
*   Collaborate with local directors & actors.

###Release Strategy



*   Launch major TV Shows during Q3-Q4 (Holiday seasons).
"""

